name: Documentation

on:
  push:
    branches: '*'
    tags: '*'
    
jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Xana
      uses: actions/checkout@v1
      with:
        path: Xana

    - name: troubleshooting 1
      run: |
        pwd
        ls

    - name: Checkout Xana gh-docs branch
      uses: actions/checkout@v1
      with:
        ref: gh-pages
        path: gh-pages
        persist-credentials: false
        fetch-depth: 0

    - name: troubleshooting 2
      run: |
        pwd
        ls
        cd ..
        pwd
        ls
        cd ..
        pwd
        ls
        echo "---"
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install docs dependencies
      run: |
        sudo apt install pandoc
        pip install --upgrade pip
        pushd Xana
        pip install numpy
        pip install -e ".[docs]"
        popd

    - name: Build docs
      run: |
        pwd
        ls
        pushd Xana/docs
        make html -e
        popd

    - name: Commit documentation changes
      run: |
        mkdir gh-pages/$GITHUB_REF/
        cp -r Xana/docs/_build/html/* gh-pages/$GITHUB_REF/
        pushd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation for $GITHUB_REF" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
        popd

    - name: Push changes
      uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
